// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aciykgfeiaympjtpookm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaXlrZ2ZlaWF5bXBqdHBvb2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzQ4NDYsImV4cCI6MjA2MDc1MDg0Nn0.43M0yqdqBdY61Pd3SzPRjIXPb7VUhV6SM1LH13eV4MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);